### ISSUE TITLE
implement process.py and pass instructions.json 

### ISSUE THREAD

**Issue by NiklasTR** [labdao/lab-equibind#23]

**Comment by thetechnocrat-dev** [comment]
Ticket came out of [this meeting](https://www.notion.so/labdao/Define-a-infrastructure-plan-for-the-next-30-days-688321647e7f4f5eac48b5d2f6131126).

First solution will probably have to be simplified to implementing a first pass common interface for ingesting jobs from json payloads.

**Comment by thetechnocrat-dev** [comment]
Current thoughts:

Add "job_id": <unique identifier> to instructions.json (later this will be produced automatically by upstream system). This is needed as a key to index result data in S3.

Use S3 bucket paths in the instructions.json instead of IPFS CIDS for this sprint iteration.

Add process.py to ganglia and include its download in the install.sh script.

process.py will convert instructions.json to a docker command and also invoke that command using a blocking subprocess call.

process.py will then send stdout result, instructions.json, and output directory to S3 with the job_id as an unique identifier key.

So producing data for this sprint will involve

1) running install.sh on an instance
2) manually creating instructions.json on the instance for diffdock 
3) running ```python process.py instructions.json``` on the instance
4) download the result data from S3 and re-uploading a transformed version for gnina input
5) manually creating instructions.json on the instance for gnina
6) running ```python process.py instructions.json``` on the instance
7) download the result data from S3 for local post analysis

**Comment by NiklasTR** [comment]
this sounds good! 

- [ ] I think what we should add is a set of instructions to benchmark the scores coming out of gnina against the ground-truth in CASF-2016. 
- [ ] I think eventually we just want to use the CID of the instruction.json as the task_id -> we called this the jobURI

**Comment by NiklasTR** [comment]
closing
